### ISSUE TITLE
Compatibility with Ad Blockers

### ISSUE THREAD

**Issue by Nzzyme** [craiu/mobiletrackers#6]
Can you please make your Master List compatible with AdGuard and other ad blockers like ublocker? Tried adding [this ](https://raw.githubusercontent.com/craiu/mobiletrackers/master/list.txt)to AdGuard but it won't filter/block the domains as the syntax for the individual rules is not in the right format.

**Comment by craiu** [comment]
Thanks for the report. I am not familiar with the AdGuard format, do you know by any chance why it doesn't like the list? After all it's just plaintext hostnames. Any advice would be welcome.

**Comment by elliotwutingfeng** [comment]
The following bash script creates lists compatible with Adblock Plus (ABP) and UBlock Origin (UBO). I use something similar for my own blocklists. The `sed` utility is required.

ABP requires the hostnames to be wrapped like this `||example.com^`, for UBO it is `||example.com^$all`.

Comment lines starting with `#` and blank lines are ignored.

```bash
sed -E '/(^#.*$|^$)/!s/^/\|\|/;/(^#.*$|^$)/!s/$/\^/' list.txt > list-ABP.txt
sed -E '/(^#.*$|^$)/!s/^/\|\|/;/(^#.*$|^$)/!s/$/\^$all/' list.txt > list-UBO.txt
```

**Comment by craiu** [comment]
Thanks Wu Tingfeng, added the versions processed by your script to the repo.
